<a href="https://colab.research.google.com/github/serenalxs/Practice/blob/main/Basic/pytorchbasic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
print(f"PyTorch Version: {torch.__version__}")

PyTorch Version: 2.10.0+cpu


# **Initialize Tensor** : Int64, float32,float 64


1. create tensor directorly

In [3]:
t = torch.tensor([1,2,3])
print(t)
print(t.dtype)

t = torch.FloatTensor([1,2,3])
print(t)
print(t.dtype)

t = torch.LongTensor([1,2,3])
print(t)
print(t.dtype)

t = torch.tensor([1,2,3],dtype = torch.float32)
print(t)
print(t.dtype)

tensor([1, 2, 3])
torch.int64
tensor([1., 2., 3.])
torch.float32
tensor([1, 2, 3])
torch.int64
tensor([1., 2., 3.])
torch.float32


2. create tensor from numpy

In [4]:
arr = np.arange(12).reshape(3,4)
print(arr)

t = torch.from_numpy(arr)
print(t)



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


# **Create random tensor matrix**

In [6]:
t = torch.rand (2,3)
print(t)
print(t.shape)
print(t.dtype)

tensor([[0.0039, 0.4686, 0.5547],
        [0.9123, 0.1087, 0.1871]])
torch.Size([2, 3])
torch.float32


In [11]:
print (torch.zeros(3))
print (torch.zeros(2,3))
print (torch.ones(2,3))


tensor([0., 0., 0.])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


create a matrix like another matrix : zero_like / ones_like

In [12]:
print ( torch.zeros_like (t) )


tensor([[0., 0., 0.],
        [0., 0., 0.]])
