<a href="https://colab.research.google.com/github/serenalxs/Practice/blob/main/pytorchbasic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
print(f"PyTorch Version: {torch.__version__}")

PyTorch Version: 2.10.0+cpu


# **Initialize Tensor** : Int64, float32,float 64


1. create tensor directorly

In [7]:
t = torch.tensor([1,2,3])
print(t)
print(t.dtype)

t = torch.FloatTensor([1,2,3])
print(t)
print(t.dtype)

t = torch.LongTensor([1,2,3])
print(t)
print(t.dtype)

tensor([1, 2, 3])
torch.int64
tensor([1., 2., 3.])
torch.float32
tensor([1, 2, 3])
torch.int64


2. create tensor from numpy

In [10]:
arr = np.arange(12).reshape(3,4)
print(arr)

t = torch.from_numpy(arr)
print(t)



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
