<a href="https://colab.research.google.com/github/serenalxs/Practice/blob/main/Basic/pytorchbasic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
print(f"PyTorch Version: {torch.__version__}")

PyTorch Version: 2.10.0+cpu


# **Initialize Tensor** : Int64, float32,float 64


1. create tensor directorly

In [3]:
t = torch.tensor([1,2,3])
print(t)
print(t.dtype)

t = torch.FloatTensor([1,2,3])
print(t)
print(t.dtype)

t = torch.LongTensor([1,2,3])
print(t)
print(t.dtype)

t = torch.tensor([1,2,3],dtype = torch.float32)
print(t)
print(t.dtype)

tensor([1, 2, 3])
torch.int64
tensor([1., 2., 3.])
torch.float32
tensor([1, 2, 3])
torch.int64
tensor([1., 2., 3.])
torch.float32


2. create tensor from numpy

In [4]:
arr = np.arange(12).reshape(3,4)
print(arr)

t = torch.from_numpy(arr)
print(t)



[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


# **Create random tensor matrix**

In [5]:
t = torch.rand (2,3)
print(t)
print(t.shape)
print(t.dtype)

tensor([[0.3676, 0.9324, 0.7445],
        [0.5892, 0.2305, 0.4179]])
torch.Size([2, 3])
torch.float32


change the type of data

In [6]:
t = torch.rand (2,3)
print (t.dtype)
s = t.type (torch.float16)
print (s.dtype)
s = t.type (torch.int)
print (s)
print (s.dtype)
s = t.type (torch.int16)
print (s)
print (s.dtype)

torch.float32
torch.float16
tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)
torch.int32
tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int16)
torch.int16


fast convert to most common used using long  (int64) and float (float32)

In [7]:
t = torch.randn(2,3)
print(t)
s = t.long()
print (s)
print (s.dtype)
s = t.float()
print (s)
print (s.dtype)

tensor([[ 0.7090, -0.4174, -1.3965],
        [ 0.7300, -1.3887,  0.7147]])
tensor([[ 0,  0, -1],
        [ 0, -1,  0]])
torch.int64
tensor([[ 0.7090, -0.4174, -1.3965],
        [ 0.7300, -1.3887,  0.7147]])
torch.float32


In [8]:
print (torch.zeros(3))
print (torch.zeros(2,3))
print (torch.ones(2,3))


tensor([0., 0., 0.])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


create a matrix like another matrix : zero_like / ones_like

In [9]:
print ( torch.zeros_like (t) )
print ( torch.rand_like (t) )
print (t.shape)
print (t.size())
print (t.size(0)) #single dimension



tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.9298, 0.4853, 0.3720],
        [0.9747, 0.1247, 0.5566]])
torch.Size([2, 3])
torch.Size([2, 3])
2


CPU or CUDA (显卡）

In [10]:
print (t.device)
print (torch.cuda.is_available())

cpu
False


**Tensor calculation**

In [11]:
t = torch.rand (2,3)
s = torch.ones_like(t)
print (t)
print (s)
print (t+s)

tensor([[0.8688, 0.0873, 0.4290],
        [0.8941, 0.1008, 0.9410]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1.8688, 1.0873, 1.4290],
        [1.8941, 1.1008, 1.9410]])


add and add_ (replace the original tensor)

In [12]:
print (t.add(s))
t.add_(s)
print(t)

tensor([[1.8688, 1.0873, 1.4290],
        [1.8941, 1.1008, 1.9410]])
tensor([[1.8688, 1.0873, 1.4290],
        [1.8941, 1.1008, 1.9410]])


matrix multiplication -- 1. may need matrix transformation (.T) 2. matrix multiplication (.malmul)

In [13]:
t = torch.rand (2,3)
s = t.T
print (t)
print (s)
k = t.matmul(t.T)
print (k)

#abbrev.
print (t @ t.T)

tensor([[0.0189, 0.2232, 0.4076],
        [0.6279, 0.2823, 0.9412]])
tensor([[0.0189, 0.6279],
        [0.2232, 0.2823],
        [0.4076, 0.9412]])
tensor([[0.2163, 0.4585],
        [0.4585, 1.3597]])
tensor([[0.2163, 0.4585],
        [0.4585, 1.3597]])


# convert tensor to numpy : .item()

In [14]:
print (t.sum().item())
print (t.mean().item())

2.500983715057373
0.4168306291103363


from numpy (.from_numpy(..)) and to numpy (.numpy)

In [15]:
t = torch.from_numpy(np.random.randn(2,3))
print (t)
print (t.numpy())

tensor([[-0.2647, -0.9820,  0.5088],
        [-0.8904, -0.0278, -3.0880]], dtype=torch.float64)
[[-0.26471228 -0.98198507  0.50880679]
 [-0.89040906 -0.02778137 -3.08800494]]


# **change tensor shape : .view() used to flatten the matrix**

In [16]:
t = torch.randn (4,6)
s = t.view (3,8)
print (t)
print (s)
print (t.view(24,1))

tensor([[-0.8135,  1.1307, -0.1950,  0.3473, -1.0561,  0.2626],
        [-0.7197,  1.2690, -0.4047, -0.2305, -1.2467,  0.4392],
        [-0.5495, -0.0688,  0.1812,  1.4815, -0.6542, -0.5580],
        [ 0.5491,  1.1460, -1.1489,  0.1417,  0.3551, -0.9272]])
tensor([[-0.8135,  1.1307, -0.1950,  0.3473, -1.0561,  0.2626, -0.7197,  1.2690],
        [-0.4047, -0.2305, -1.2467,  0.4392, -0.5495, -0.0688,  0.1812,  1.4815],
        [-0.6542, -0.5580,  0.5491,  1.1460, -1.1489,  0.1417,  0.3551, -0.9272]])
tensor([[-0.8135],
        [ 1.1307],
        [-0.1950],
        [ 0.3473],
        [-1.0561],
        [ 0.2626],
        [-0.7197],
        [ 1.2690],
        [-0.4047],
        [-0.2305],
        [-1.2467],
        [ 0.4392],
        [-0.5495],
        [-0.0688],
        [ 0.1812],
        [ 1.4815],
        [-0.6542],
        [-0.5580],
        [ 0.5491],
        [ 1.1460],
        [-1.1489],
        [ 0.1417],
        [ 0.3551],
        [-0.9272]])


multiple dimension

In [17]:
t = torch.randn (2,3,4,2)
print (t)
print (t.view (2, 3*4*2))

tensor([[[[ 0.7754,  0.6025],
          [ 0.1438, -0.6138],
          [-0.0074, -0.6852],
          [ 0.9176,  0.0392]],

         [[-0.9712,  1.7216],
          [ 1.4968, -3.1894],
          [ 0.5519, -0.9385],
          [ 0.9653, -0.0991]],

         [[-1.4366,  0.8646],
          [ 0.0667,  1.8296],
          [-0.6691,  1.6402],
          [ 0.3320, -0.0451]]],


        [[[ 1.6875, -0.7616],
          [-1.1562, -1.4643],
          [ 0.6965, -0.8690],
          [-0.7239,  2.3989]],

         [[-1.1663,  0.3928],
          [-0.0532,  0.3780],
          [ 1.9981, -1.6705],
          [-0.8263,  2.7073]],

         [[ 1.6143,  1.0285],
          [-1.7629,  1.5407],
          [-0.5423, -1.1326],
          [-0.1944, -0.3353]]]])
tensor([[ 0.7754,  0.6025,  0.1438, -0.6138, -0.0074, -0.6852,  0.9176,  0.0392,
         -0.9712,  1.7216,  1.4968, -3.1894,  0.5519, -0.9385,  0.9653, -0.0991,
         -1.4366,  0.8646,  0.0667,  1.8296, -0.6691,  1.6402,  0.3320, -0.0451],
        [ 1.6875, -0.

data add ( using view (1, ...) ): add one dimension outside
or remove 1 dimension (.squeeze ()) : remove 1 level dimension

In [18]:
t = torch.randn (2,3,4)
print (t)
t = t.view ( 1,2,3,4)
print (t)
print (t.squeeze())
print (torch.squeeze(t))


tensor([[[ 0.5998, -0.8763, -1.9626, -1.8487],
         [-0.2045, -0.5976, -1.9455,  0.3747],
         [-0.1450,  0.9584, -0.3384, -0.5513]],

        [[ 0.2596, -0.2252, -1.4660,  1.7190],
         [-0.3951, -2.0324,  1.0783, -0.6538],
         [-1.1392,  0.2411,  1.2748, -0.2667]]])
tensor([[[[ 0.5998, -0.8763, -1.9626, -1.8487],
          [-0.2045, -0.5976, -1.9455,  0.3747],
          [-0.1450,  0.9584, -0.3384, -0.5513]],

         [[ 0.2596, -0.2252, -1.4660,  1.7190],
          [-0.3951, -2.0324,  1.0783, -0.6538],
          [-1.1392,  0.2411,  1.2748, -0.2667]]]])
tensor([[[ 0.5998, -0.8763, -1.9626, -1.8487],
         [-0.2045, -0.5976, -1.9455,  0.3747],
         [-0.1450,  0.9584, -0.3384, -0.5513]],

        [[ 0.2596, -0.2252, -1.4660,  1.7190],
         [-0.3951, -2.0324,  1.0783, -0.6538],
         [-1.1392,  0.2411,  1.2748, -0.2667]]])
tensor([[[ 0.5998, -0.8763, -1.9626, -1.8487],
         [-0.2045, -0.5976, -1.9455,  0.3747],
         [-0.1450,  0.9584, -0.3384, -0.5

# **Gradient**


activate gradient : requires_grad = True

activate trace back : .backward() , only applied to scalar (number, not to vector)

look for **gradient** : .grad

look for **gradient function** : .grad_fn , the first derivative doesn't have gradient function

cut off the trace back : .detach()


In [42]:
t = torch.ones(2,2,requires_grad = True)
print (t)
print (t.requires_grad)

y = t + 5
z = y * 2
out = z.mean()

print(out)
print (y.grad_fn)
print(z.grad_fn)
print (out.grad_fn)

#activate backward trace : backward can only be applied to a scalar (number, not valid to vector)
out.backward()

# after being activated, can track original step's gradient
print("d(out)/d(t):", t.grad)

result = out.detach()
print (result.requires_grad)




tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
True
tensor(12., grad_fn=<MeanBackward0>)
d(out)/d(t): tensor([[0.5000, 0.5000],
        [0.5000, 0.5000]])
False


# **Don't need to trace gradient**


Method 1: change original .requires_grad_(True/False)

Method 2: with torch.no_grad()

In [38]:
# method 2 :

with torch.no_grad () :
  y = t +2
  print (y)
  print (y.requires_grad)

tensor([[3., 3.],
        [3., 3.]])
False


In [41]:
# method 1:
t = torch.ones (2,2,requires_grad =True)
t.requires_grad_(False)
print (t)
print (t.requires_grad)

tensor([[1., 1.],
        [1., 1.]])
False
